import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { SignInButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

dayjs.extend(relativeTime);

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  const CreatePostWizard = () => {
    const { user } = useUser();

    if (!user) return null;

    return (<div className="flex w-full gap-3">
      <Image
        alt="Profile image"
        src={user.profileImageUrl}
        width={56}
        height={56}
        className="h-14 w-14 rounded-full"
      />
      <input placeholder="Type some emojis!" className="bg-transparent grow outline-none" />
    </div>);
  }

  type PostWithUser = RouterOutputs["posts"]["getAll"][number];
  const PostView = (props: PostWithUser) => {
    const { post, author } = props;
    return (
      <div className="flex border-b border-slate-400 p-4 gap-3" key={post.id}>
        <Image
          src={author.profileImageUrl}
          alt={`${author.username}'s profile picture`}
          width={56}
          height={56}
          className="h-14 w-14 rounded-full"
        />
        <div className="flex flex-col">
          <div className="flex font-bold text-slate-300 gap-1">
            <span>{`@${author.username}`}</span>
            <span className="font-thin">{` · ${dayjs(post.createdAt).fromNow()}`}</span>
          </div>
          <span>{post.content}</span>
        </div>
      </div>
    )
  }

  if (!data || isLoading) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x md:max-w-2xl border-slate-400">
          <div className="flex border-b border-slate-400 p-4">
            <>
              {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
              {!!user.isSignedIn && <CreatePostWizard />}
            </>
          </div>
          <div className="flex flex-col">
            {data.map(({ post, author }) => (
              <PostView key={post.id} post={post} author={author} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
